server:
  port: 8080


spring:
  application:
    name: gateway

  cloud:
    consul:
      host: localhost
      port: 8500


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
